name: Latest Github Activity

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-gh-activity:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: NicolasRoehm/NicolasRoehm@master
        with:
          comment_tag_name: GITHUB-ACTIVITY 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
